name: Tests
on: push

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.1.4", "1.1.11"]
        os: [ubuntu-20.04,]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Config poetry
        run: poetry config virtualenvs.create false --local

      - name: Install dependencies
        run: poetry install --no-root
      
      - name: Linting
        run: pylama
        
      - name: Run tests
        run: pytest
