name: Tests
on: push

jobs:
  tests:
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
          MONGO_INITDB_DATABASE: test
        options: >-
                --health-cmd mongo
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
        ports:
          - 27017:27017
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.1.4", "1.1.11"]
        os: [ubuntu-20.04,]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Config poetry
        run: poetry config virtualenvs.create false --local

      - name: Install dependencies
        run: poetry install --no-root

      - name: Linting
        run: pytest --pylama
        env:
          DOISTER_API_KEY: ${DOISTER_API_KEY}
          DOISTER_ENV: ${{ secrets.DOISTER_ENV }}
          DOISTER_HOST: ${{ secrets.DOISTER_HOST }}
          DOISTER_AIRTABLE__TOKEN: ${{ secrets.DOISTER_AIRTABLE__TOKEN }}
          DOISTER_AIRTABLE__BASE_ID: ${{ secrets.DOISTER_AIRTABLE__BASE_ID }}
          DOISTER_MONGO__SERVER: ${{ secrets.DOISTER_MONGO__SERVER }}
          DOISTER_TELEGRAM__BOT_NAME: ${{ secrets.DOISTER_TELEGRAM__BOT_NAME }}
          DOISTER_TELEGRAM__BOT_TOKEN: ${{ secrets.DOISTER_TELEGRAM__BOT_TOKEN }}
          DOISTER_TODOIST__CLIENT_ID: ${{ secrets.DOISTER_TODOIST__CLIENT_ID }}
          DOISTER_TODOIST__CLIENT_SECRET: ${{ secrets.DOISTER_TODOIST__CLIENT_SECRET }}
          DOISTER_TODOIST__STATE_STRING: ${{ secrets.DOISTER_TODOIST__STATE_STRING }}

